Add license-check job to build workflow
Added a license-check job to ensure all Java files contain the GNU General Public License header.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,9 +45,27 @@ jobs:
           archive: false
           if-no-files-found: error
 
+  license-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v7
+      - name: Look for license phrase
+        run: |
+          outfile=$(mktemp)
+          find . -name "*.java" | xargs grep -L "GNU General Public License" > ${outfile}
+          if [ -s "${outfile}" ]
+          then
+            echo "License headers missing on the following files:"
+            cat ${outfile}
+            exit 1
+          else
+            echo "License headers appear to be valid!"
+          fi
+
   build-native:
     name: bt and st on ${{ matrix.os }}-${{ matrix.arch }}
-    needs: [build-java]
+    needs: [build-java, license-check]
     runs-on: ${{ matrix.label }}
     strategy:
       matrix:
